rails/section-03/mdb/config/routes.rb
Rails.application.routes.draw do
  resources :actors
  resources :shows
  resources :movies
end

rails/section-03/mdb/app/models/actor.rb
class Actor < ApplicationRecord
    belongs_to :production, polymorphic: true
end

rails/section-03/mdb/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :actors, as: :production, dependent: :destroy
end

rails/section-03/mdb/app/models/show.rb
class Show < ApplicationRecord
    has_many :actors, as: :production, dependent: :destroy
end

rails/section-03/mdb/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[ show edit update destroy ]

  # GET /actors or /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1 or /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors or /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully created." }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1 or /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to actor_url(@actor), notice: "Actor was successfully updated." }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1 or /actors/1.json
  def destroy
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url, notice: "Actor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def actor_params
      params.require(:actor).permit(:name)
    end
end

rails/section-03/mdb/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:title, :duration)
    end
end

rails/section-03/mdb/app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[ show edit update destroy ]

  # GET /shows or /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1 or /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: "Show was successfully created." }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: "Show was successfully updated." }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: "Show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:title, :episodes)
    end
end

rails/section-03/mdb/app/helpers/actors_helper.rb
module ActorsHelper
end

rails/section-03/mdb/app/helpers/movies_helper.rb
module MoviesHelper
end

rails/section-03/mdb/app/helpers/shows_helper.rb
module ShowsHelper
end

rails/section-03/mdb/app/views/actors/_actor.html.erb
<div id="<%= dom_id actor %>">
  <p>
    <strong>Name:</strong>
    <%= actor.name %>
  </p>

</div>

rails/section-03/mdb/app/views/actors/_form.html.erb
<%= form_with(model: actor) do |form| %>
  <% if actor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails/section-03/mdb/app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Show this actor", @actor %> |
  <%= link_to "Back to actors", actors_path %>
</div>

rails/section-03/mdb/app/views/actors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Actors</h1>

<div id="actors">
  <% @actors.each do |actor| %>
    <%= render actor %>
    <p>
      <%= link_to "Show this actor", actor %>
    </p>
  <% end %>
</div>

<%= link_to "New actor", new_actor_path %>

rails/section-03/mdb/app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render "form", actor: @actor %>

<br>

<div>
  <%= link_to "Back to actors", actors_path %>
</div>

rails/section-03/mdb/app/views/actors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @actor %>

<div>
  <%= link_to "Edit this actor", edit_actor_path(@actor) %> |
  <%= link_to "Back to actors", actors_path %>

  <%= button_to "Destroy this actor", @actor, method: :delete %>
</div>

rails/section-03/mdb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7Mdb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails/section-03/mdb/app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails/section-03/mdb/app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= movie.duration %>
  </p>

</div>

rails/section-03/mdb/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

rails/section-03/mdb/app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

rails/section-03/mdb/app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

rails/section-03/mdb/app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

rails/section-03/mdb/app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :episodes, style: "display: block" %>
    <%= form.number_field :episodes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails/section-03/mdb/app/views/shows/_show.html.erb
<div id="<%= dom_id show %>">
  <p>
    <strong>Title:</strong>
    <%= show.title %>
  </p>

  <p>
    <strong>Episodes:</strong>
    <%= show.episodes %>
  </p>

</div>

rails/section-03/mdb/app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Show this show", @show %> |
  <%= link_to "Back to shows", shows_path %>
</div>

rails/section-03/mdb/app/views/shows/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shows</h1>

<div id="shows">
  <% @shows.each do |show| %>
    <%= render show %>
    <p>
      <%= link_to "Show this show", show %>
    </p>
  <% end %>
</div>

<%= link_to "New show", new_show_path %>

rails/section-03/mdb/app/views/shows/new.html.erb
<h1>New show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Back to shows", shows_path %>
</div>

rails/section-03/mdb/app/views/shows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @show %>

<div>
  <%= link_to "Edit this show", edit_show_path(@show) %> |
  <%= link_to "Back to shows", shows_path %>

  <%= button_to "Destroy this show", @show, method: :delete %>
</div>