rails/section-04/customer/config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :orders
  root "customers#index"
end

rails/section-04/customer/app/models/customer.rb
class Customer < ApplicationRecord

    validates :first_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
    validates :last_name, presence: true, format: { with: /\A[a-z\-' ]+\z/i }
    validates :phone, presence: true
    validates :phone, numericality: { only_integer: true }
    validates :phone, length: { is: 10 }
    validates :email, presence: true, email: true

    def full_name
        "#{first_name} #{last_name}"
    end

    has_many :orders
end

rails/section-04/customer/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  validates :product_name, presence: true
  validates :product_count, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :customer_id, presence: true
end

rails/section-04/customer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/section-04/customer/app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer, notice: "Customer was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: "Customer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    begin
      @customer.destroy
      redirect_to customers_url, notice: "The customer record was successfully deleted."
    rescue ActiveRecord::InvalidForeignKey
      flash[:alert] = "That customer record could not be deleted because the customer has orders."
      # redirect to the custormer page or back to the list as backup option
      redirect_back(fallback_location: customers_url)
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      # debugger
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception")
      flash.alert = e.to_s
      redirect_to customers_path
    end
end

rails/section-04/customer/app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end


  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to @order, notice: "Order was was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end


  def update
    if @order.update(order_params)
      redirect_to @order, notice: "Order was was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end


  def destroy
    @order.destroy
    redirect_to orders_url, notice: "Order was successfully destroyed."
  end


  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:product_name, :product_count, :customer_id)
    end
end

rails/section-04/customer/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/section-04/customer/app/helpers/customers_helper.rb
module CustomersHelper
end

rails/section-04/customer/app/helpers/orders_helper.rb
module OrdersHelper
end

rails/section-04/customer/app/views/customers/_customer.html.erb
<div class="card mb-2">
  <div class="card-body">
    <h5 class="card-title"><%= @customer.full_name %></h5>
    <p class="card-text"><strong>Email:</strong> <%= @customer.email %></p>
    <p class="card-text"><strong>Phone:</strong> <%= @customer.phone %></p>

    <div>
      <%= render "shared/buttons/edit_button", object: @customer %>
      <%= render "shared/buttons/delete_button", object: @customer %>
    </div>
  </div>
</div>

rails/section-04/customer/app/views/customers/_customer_list.html.erb
<% if customers.empty? %>
  <p>There are no Customers. Go ahead and create first one!</p>
<% else %>
    <table class="table">
        <thead>
            <tr>
                <th class="col-md-6">Name</th>
                <th class="col-md-2">Orders</th>
                <th class="col-md-4">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% customers.each do | customer | %>
                <tr>
                    <td><%= customer.full_name %></td>
                    <td><%= customer.orders.count %></td>
                    <td>
                        <%= render "shared/buttons/show_button", object: customer %>
                        <%= render "shared/buttons/edit_button", object: customer %>
                        <%= render "shared/buttons/delete_button", object: customer %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

rails/section-04/customer/app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>

  <%= render "shared/errors/form_message", object: customer %>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: "form-control" %>
    </div>

    <div class="col-md-6 mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="d-flex justify-content-start gap-2">
    <%= render "shared/buttons/cancel_button",
     path: customer.new_record? ? customers_path : customer_path 
    %>
    <%= render "shared/buttons/save_button", form: form %>
  </div>

<% end %>

rails/section-04/customer/app/views/customers/edit.html.erb
<h3>Editing Customer</h3>

<%= render "form", customer: @customer %>

rails/section-04/customer/app/views/customers/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h3>Customers</h3>
  <%= render "shared/buttons/new_button", model: Customer %> 
</div>
<%= render "customer_list", customers: @customers %>

rails/section-04/customer/app/views/customers/new.html.erb
<h3>New Customer Form</h3>

<%= render "form", customer: @customer %>

rails/section-04/customer/app/views/customers/show.html.erb
<div class="container mt-3">
  
  <h3>Customer Details</h3>
  <%= render "customer" %>

  <h3>Orders</h3>
  <%= render "orders/order_list", orders: @customer.orders %>

  <%= render "shared/buttons/back_button", object: @customer %>

</div>

rails/section-04/customer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>R7Additional</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="bg-primary text-center px-1 py-2 banner-background">
        <div class="py-5">
          <h1 class="display-4 text-dark font-weight-bold text-shadow">Customers and Orders</h1>
          <p class="lead text-dark px-2 py-1 text-shadow">This is a sample application that associates orders with customers.</p>
        </div>
      </div>

      <nav class="navbar navbar-expand navbar-light mb-2">
        <div class=container my-4">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                <%= icon("fa-solid", "user") %> Customers
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="<%= customers_path %>">Customer List</a></li>
                <li><a class="dropdown-item" href="<%= new_customer_path %>">New Customer</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                <%= icon("fa-solid", "file-alt") %> Orders
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="<%= orders_path %>">Order List</a></li>
                <li><a class="dropdown-item" href="<%= new_order_path %>">New Order</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
      
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      
      <div><%= yield %></div>
    </div>
  </body>
</html>

rails/section-04/customer/app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>

  <%= render "shared/errors/form_message", object: order %>

  <div class="row">

    <div class="col-md-4 mb-3">
      <%= form.label :customer_id %>
      <%= form.collection_select :customer_id, Customer.all, :id, :full_name, { prompt: "Select a Customer" }, { class: "form-control" } %>
    </div>

    <div class="col-md-5 mb-3">
      <%= form.label :product_name %>
      <%= form.text_field :product_name, class: "form-control" %>
    </div>

    <div class="col-md-3 mb-3">
      <%= form.label :product_count %>
      <%= form.number_field :product_count, class: "form-control" %>
    </div>

  </div>

  <div class="d-flex justify-content-start gap-2">
    <%= render "shared/buttons/cancel_button",
     path: order.new_record? ? orders_path : order_path 
    %>
    <%= render "shared/buttons/save_button", form: form %>
  </div>
<% end %>

rails/section-04/customer/app/views/orders/_order.html.erb
<div class="col-sm-12 col-md-6 col-lg-4 col-xl-3 mb-4">
  <div class="card border border-2 border-success p-1 h-100">
    <div class="card-header">
      <%= order.product_name %>
    </div>
    <div class="card-body">
      <p class="card-text">
        <strong>Count:</strong>
        <%= order.product_count %>
      </p>
      <p class="card-text">
        <strong>Customer:</strong>
        <%= order.customer.full_name %>
      </p>
    </div>
    <div class="card-footer bg-transparent">
      <%= render "shared/buttons/show_button", object: order %>
      <%= render "shared/buttons/edit_button", object: order %>
      <%= render "shared/buttons/delete_button", object: order %>
    </div>
  </div>
</div>

rails/section-04/customer/app/views/orders/_order_list.html.erb
<!-- app/views/shared/buttons/_order_list.html.erb -->
<% if orders.empty? %>
  <p>This Customer has no Orders</p>
<% else %>
    <div class="card">
        <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <% @customer.orders.each do |order| %>
                <tr>
                    <td><%= order.product_name %></td>
                    <td><%= order.product_count %></td>
                    <td>
                        <%= render "shared/buttons/show_button", object: order %>
                        <%= render "shared/buttons/edit_button", object: order %>
                        <%= render "shared/buttons/delete_button", object: order %>
                    </td>
                </tr>
            <% end %>
            </tbody>
        </table>
        </div>
    </div>
<% end %>

rails/section-04/customer/app/views/orders/edit.html.erb
<h3>Edit Order</h3>
<%= render "form", order: @order %>

rails/section-04/customer/app/views/orders/index.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h3>Orders</h3>
  <%= render "shared/buttons/new_button", model: Order %> 
</div>
<div class="row">
  <% @orders.each do |order| %>
    <%= render order %>
  <% end %>
</div>

rails/section-04/customer/app/views/orders/new.html.erb
<h3>New Order</h3>
<%= render "form", order: @order %>

rails/section-04/customer/app/views/orders/show.html.erb
<div class="container mt-3">
  <h3>Order Details</h3>

  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @order.product_name %></h5>
      <p class="card-text"><strong>Product Count:</strong> <%= @order.product_count %></p>
      <p class="card-text"><strong>Customer:</strong> <%= @order.customer.full_name %></p>

      <div>
        <%= render "shared/buttons/edit_button", object: @order %>
        <%= render "shared/buttons/delete_button", object: @order %>
      </div>
    </div>
  </div>

  <%= render "shared/buttons/back_button", object: @order %>
</div>